### ISSUE TITLE
compile_APPR_mex.m appears to be broken out of the box

### ISSUE THREAD

**Issue by CrazyWhatsIt** [LJeub/LocalCommunities#1]
Apologies, I work mostly with GitLab and don't have a professional github account.

compile_APPR_mex.m appears to have two bad paths, one to the APPR source and one to the matlab matrix source. See lines 18 and 19:

```includes=['-I',location,'/ACLcut/APPR/matlab_matrix'];```
and
```compiles=strcat(location,'/ACLcut/APPR/' {'APPR/APPR','matlab_matrix/full','matlab_matrix/sparse'},'.cpp');```

I see that the last commit on the file is "Update some documentation and clean up folder structure". I'm guessing this script was at the top level and was later moved to the ACLcut directory. The "/ACLcut" sub-string can be safely removed from each path.

```includes=['-I',location,'/APPR/matlab_matrix'];```
and 
```compiles=strcat(location,'/APPR/', {'APPR/APPR','matlab_matrix/full','matlab_matrix/sparse'},'.cpp');```

The above works just fine.

Regards,

Daniel Schaefer

**Comment by LJeub** [comment]
You are right, I moved the script and forgot to update the paths. This is now fixed.

Thank you,

Lucas Jeub
